name: Version Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release_pr:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@main
        with:
          node-version: lts/*

      - run: yarn

      - uses: changesets/action@v1
        with:
          version: yarn version-packages
        env:
          # note that we're not using the GH token provided by Actions here because Actions has a rule that Actions
          # will not run as the result of another Action so CI wouldn't run on the release PRs then
          # we can get around it by using a personal access token from a GH account
          GITHUB_TOKEN: ${{ secrets.KEYSTONE_RELEASE_BOT_GITHUB_TOKEN }}
